cc_library(
    name = "proto_util",
    srcs = ["proto_util.cc"],
    hdrs = ["proto_util.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//analyzer/proto:analyzer_cc_proto",
        "@com_github_google_glog//:glog",
        "@com_google_absl//absl/status",
    ],
)
