include ../../scripts/Makefile.lib

check_2_1:
	$(MAKE) -C cmd run check_rules=misra_c_2012/rule_2_1 compile_commands_path=$(compile_commands_path)

check_2_2:
	$(MAKE) -C cmd run check_rules=misra_c_2012/rule_2_2 compile_commands_path=$(compile_commands_path)

check_9_1:
	$(MAKE) -C cmd run check_rules=misra_c_2012/rule_9_1 compile_commands_path=$(compile_commands_path)

check_12_2:
	$(MAKE) -C cmd run check_rules=misra_c_2012/rule_12_2 compile_commands_path=$(compile_commands_path)

check_13_1:
	$(MAKE) -C cmd run check_rules=misra_c_2012/rule_13_1 compile_commands_path=$(compile_commands_path)

check_14_1:
	$(MAKE) -C cmd run check_rules=misra_c_2012/rule_14_1 compile_commands_path=$(compile_commands_path)

check_14_3:
	$(MAKE) -C cmd run check_rules=misra_c_2012/rule_14_3 compile_commands_path=$(compile_commands_path)

check_18_1:
	$(MAKE) -C cmd run check_rules=misra_c_2012/rule_18_1 compile_commands_path=$(compile_commands_path)

check_18_2:
	$(MAKE) -C cmd run check_rules=misra_c_2012/rule_18_2 compile_commands_path=$(compile_commands_path)

check_18_6:
	$(MAKE) -C cmd run check_rules=misra_c_2012/rule_18_6 compile_commands_path=$(compile_commands_path)

check_18_3:
	$(MAKE) -C cmd run check_rules=misra_c_2012/rule_18_3 compile_commands_path=$(compile_commands_path)

check_19_1:
	$(MAKE) -C cmd run check_rules=misra_c_2012/rule_19_1 compile_commands_path=$(compile_commands_path)

check_21_13:
	$(MAKE) -C cmd run check_rules=misra_c_2012/rule_21_13 compile_commands_path=$(compile_commands_path)

check_21_14:
	$(MAKE) -C cmd run check_rules=misra_c_2012/rule_21_14 compile_commands_path=$(compile_commands_path)

check_21_17:
	$(MAKE) -C cmd run check_rules=misra_c_2012/rule_21_17 compile_commands_path=$(compile_commands_path)

check_21_18:
	$(MAKE) -C cmd run check_rules=misra_c_2012/rule_21_18 compile_commands_path=$(compile_commands_path)

check_22_1:
	$(MAKE) -C cmd run check_rules=misra_c_2012/rule_22_1 compile_commands_path=$(compile_commands_path)

check_22_2:
	$(MAKE) -C cmd run check_rules=misra_c_2012/rule_22_2 compile_commands_path=$(compile_commands_path)

check_22_3:
	$(MAKE) -C cmd run check_rules=misra_c_2012/rule_22_3 compile_commands_path=$(compile_commands_path)

check_22_4:
	$(MAKE) -C cmd run check_rules=misra_c_2012/rule_22_4 compile_commands_path=$(compile_commands_path)

check_22_5:
	$(MAKE) -C cmd run check_rules=misra_c_2012/rule_22_5 compile_commands_path=$(compile_commands_path)

check_22_6:
	$(MAKE) -C cmd run check_rules=misra_c_2012/rule_22_6 compile_commands_path=$(compile_commands_path)

check_22_7:
	$(MAKE) -C cmd run check_rules=misra_c_2012/rule_22_7 compile_commands_path=$(compile_commands_path)
