# NaiveSystems Analyze - A tool for static code analysis
# Copyright (C) 2023  Naive Systems Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

SCRIPTS_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

ROOT := $(abspath $(SCRIPTS_DIR)..)
OUT := $(ROOT)/out

export GOPATH := $(OUT)
PATH := $(OUT)/bin:$(PATH)
PROTOC := $(OUT)/bin/protoc
ifeq ($(shell uname -sm),Darwin arm64)
	PROTOC := $(OUT)/bin/darwin_arm64_protoc
endif

PWD := $(shell pwd)

protoc = $(PROTOC) -I$(ROOT) \
      -I$(ROOT)/third_party/github.com/protocolbuffers/protobuf/src \
      --go_out=$(ROOT) $(PWD)/$(1)

NODENAME := $(shell uname -n)
ifeq ($(NODENAME),lhw13)
BAZEL_OPTS := --config=lhw13
else
BAZEL_OPTS :=
endif
